services:
  app:
    container_name: "spring-boot-app"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    container_name: "mysql-db"
    image: "mysql:latest"
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root-password"
      MYSQL_DATABASE: "sb-test-db"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
